### ISSUE TITLE
I've tried for a long time, but I can't solve this problem. I need your help very much.（SystemError: google/protobuf/pyext/descriptor.cc:354: bad argument to internal function）

### ISSUE THREAD

**Issue by YingkaiD** [AI-secure/VeriGauge#3]
**I've tried for a long time, but I can't solve this problem. I need your help very much.**
**When I run model.py, the following error is prompted：**
`/home/kai/anaconda3/envs/V_M/bin/python3.6 `/home/kai/Documents/VeriGauge-master/model.py`
Traceback (most recent call last):
  File "/home/kai/Documents/VeriGauge-master/model.py", line 4, in <module>
    import models.recurjac_model
  File "/home/kai/Documents/VeriGauge-master/models/recurjac_model.py", line 5, in <module>
    import tensorflow as tf
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow/__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1007, in _handle_fromlist
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 17, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/home/kai/anaconda3/envs/V_M/lib/python3.6/site-packages/tensorflow_core/core/framework/function_pb2.py", line 463, in <module>
    '__module__' : 'tensorflow.core.framework.function_pb2'
SystemError: google/protobuf/pyext/descriptor.cc:354: bad argument to internal function`
**The same error occurs when I try to run the following code：**
`import models.crown_ibp_model
import models.recurjac_model`
**But when I only run the following code, the error does not appear：**
`import models.crown_ibp_model`
or
`import models.recurjac_model`

**Thank you very much for your help**

**Comment by llylly** [comment]
unfortunately, I could not reproduce this error on my computer.
 
Here is the trace on my side:

```
~/anaconda3/bin/python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import models.crown_ibp_model
>>> import models.recurjac_model
>>> 
```

The package versions are:

- Python: 3.7.6
- Tensorflow: 1.15.2
- Pytorch: 1.6.0
- CUDA: 10.2

Hope this information helps!
